Sdk 4536 se refactor
tonlabs/evernode-se pull request #132
Opened 2023-03-29 11:19 UTC by melsomino

2023-03-29 13:00 UTC, d3p requested changes

2023-03-29 13:00 UTC, d3p commented on node/src/tests/test_ton_node_engine.rs
> +
empty file

2023-03-31 11:54 UTC, AlexeyVavilin approved these changes

2023-03-31 13:05 UTC, d3p commented
@melsomino check unit-test they are with errors

2023-03-31 13:39 UTC, merged